### PR TITLE
Fix offline charging on huameme

### PR DESCRIPTION
**Pull request by penn5**
As usual, its untested.

### CODE REVIEW

**Comment by peaktogooo** [comment]
lol k

**Comment by phhusson** [comment]
/etc is usually a symlink to /system/etc. Isn't it the case there?

**Comment by penn5** [comment]
Okay after a lot of force pushing I've got it all good, from what I can see.

**Comment by penn5** [comment]
BTW it's down to <700mb

**Comment by phhusson** [comment]
700mb? That's a lot :p

**Comment by penn5** [comment]
:P
i hope thats a joke.

**Comment by penn5** [comment]
oh lmao
i mistyped
i meant <700kb

**Comment by penn5** [comment]
694kb iirc

**Comment by phhusson** [comment]
I don't understand the point of  huawei_charger/Android.mk ...?
Just copy everything to system/etc/charger and that's it?

**Comment by penn5** [comment]
not quite... in base.mk i copy the files however i make the symlinks in Android.mk
I didn't want to put it in base.mk because there are so many files to symlink and the paths have to be hardcoded

> I don't understand the point of huawei_charger/Android.mk ...?
> Just copy everything to system/etc/charger and that's it?

**Comment by phhusson** [comment]
Ok, took me a lot of time to understand correctly. -_-'
I thought the symlinks were leftover from previous attempts, but no

**Comment by phhusson** [comment]
Can you confirm this current version works?
Looks ok to merge

**Comment by penn5** [comment]
> Can you confirm this current version works?
> Looks ok to merge

i cant check, ive never actually built your rom :P but I've fixed an obvious bug that i should have spotted sooner; idk if there are more

only real test is building; if it builds, its sure to work

**Comment by penn5** [comment]
Yay, lets hope it actually builds...

**Pull request merged**
