### PR TITLE
Add lag fixes by default for Moto E5 devices

### PR DESCRIPTION
**Pull request by yourordinarycat**
Add debug props for fixing lag on Moto E5 devices

### CODE REVIEW

**Comment by phhusson** [comment]
Isn't just `setprop debug.sf.latch_unsignaled 1` enough?
Also, put it in skia opengl section, not there

**Comment by yourordinarycat** [comment]
Sorry, will edit it. And yes, it isn't enough for some reason, I tried but lag was still there. Let me have time to edit it…
BTW where's that section? IDK if my eyes are damaged, but I can't find it

**Comment by yourordinarycat** [comment]
Updated

**Comment by pcamposu** [comment]
You should remove Hannah, in that variant the lag does not happen,

**Comment by yourordinarycat** [comment]
@GripKrieger I added Hannah because of rhannah, where lag happens. But I'll edit it.
Edit: Now it should be fine

**Comment by pcamposu** [comment]
i'm testing in nora but only `setprop debug.sf.hw 1 setprop debug.sf.latch_unsignaled 1` and works smooth, idk if debug.egl.hw isn't necessary

**Pull request closed without merging**
