### PR TITLE
Fix not booting on A6+

### PR DESCRIPTION
**Pull request by Royna2544**
Reopened

### CODE REVIEW

**Comment by phhusson** [comment]
Please send me your vendor/etc/selinux

**Comment by Royna2544** [comment]
Here it is
[selinux.zip](https://github.com/phhusson/device_phh_treble/files/6081833/selinux.zip)

**Comment by phhusson** [comment]
thanks

Le jeu. 4 mars 2021 à 09:07, roynatech2544 <notifications@github.com> a
écrit :

**Comment by phhusson** [comment]
I'm asking because:
- Same Android version as vendor supposedly booted (since it's a google
requirement to boot GSI)
- I have similar issue (audio HAL not starting because of SELinux denials
to vendor files) on some mediatek devices

So I'm thinking that this isn't the actual correct fix, and I need to
investigate deeper what is really the issue. (I'm fine with having merged
this though, no worries!)

Le jeu. 4 mars 2021 à 09:07, roynatech2544 <notifications@github.com> a
écrit :

**Comment by phhusson** [comment]
How did you test it?

It doesn't even build!

**Pull request merged**
