### PR TITLE
Add symbolic link to enable Huawei's offline charge

### PR DESCRIPTION
**Pull request by ponces**
Not sure if this should be done using a symbolic link or a mount command.
Please advise and I will add a new PR.

### CODE REVIEW

**Comment by ponces** [comment]
Original idea from the thread of @Dil3mm4 - https://forum.xda-developers.com/project-treble/trebleenabled-device-development/huawei-offline-charge-fix-huawei-treble-t3817944

**Comment by phhusson** [comment]
I have no /vendor/etc/charger on my Mate 9...?

**Comment by ponces** [comment]
Maybe it only works on hi6250...
Can you confirm or disprove this, @Dil3mm4 ?

**Comment by Dil3mm4** [comment]
Disprove, is not shipped by OEM.
Alberto probably installed my zip that inherits them under vendor/etc/charger

For reference: https://forum.xda-developers.com/project-treble/trebleenabled-device-development/huawei-offline-charge-fix-huawei-treble-t3817944

2018-09-29 15:53 GMT+02:00, Alberto Ponces <notifications@github.com>:

**Comment by ponces** [comment]
> Disprove, is not shipped by OEM. Alberto probably installed my zip that inherits them under vendor/etc/charger For reference: https://forum.xda-developers.com/project-treble/trebleenabled-device-development/huawei-offline-charge-fix-huawei-treble-t3817944 2018-09-29 15:53 GMT+02:00, Alberto Ponces <notifications@github.com>:
> […](#)
> Maybe it only works on hi6250... Can you confirm or disprove this, @Dil3mm4 ? -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#48 (comment)](https://github.com/phhusson/device_phh_treble/pull/48#issuecomment-425646906)

Yeah, you are right. I didn't remember the "zip" step, sorry.
However, the symbolic link would only be applied if the folder /vendor/etc/charger exists and a folder/symbolic link does not exist on /system/etc/charger.
So I guess it would be safe to apply it when both of these circumstances are true...

What do you think?

**Comment by Dil3mm4** [comment]
Well, the actual best solution would be to ship untouched system images, with extra packages. 
(e.g. System.img + Huawei_Extras.zip separately that could implement HwCamera, NFC, Charger images and etc.) 
@phhusson already had some ideas for that, but guess he got cluttered by other stuff that had far higher priority. 

About the symbolic link, well, it may just be of no use if people doesn't get to install the zip for the charger image and also this would lead to confusion for the average Joe, redirecting him back and forth.

**Comment by ponces** [comment]
I guess you're right...
I'll close the pull request then. Thank you both for your help anyway!

**Pull request closed without merging**
