### PR TITLE
Fix HW Keymaster on Samsung Galaxy M20

### PR DESCRIPTION
**Pull request by SamarV-121**
* Use keystore hal from Oreo (SM-M205F - M205FDDU1ASC1)

### CODE REVIEW

**Comment by SamarV-121** [comment]
Logcat: https://del.dog/tivujeposu

**Comment by SamarV-121** [comment]
@phhusson

**Comment by phhusson** [comment]
That's proprietary code, I don't want to include that.

**Comment by SamarV-121** [comment]
Kk

**Pull request closed without merging**
