### PR TITLE
Switch to SW Keymaster on Samasung Galaxy M20, M30

### PR DESCRIPTION
**Pull request by SamarV-121**
* Fixes screen lock

### CODE REVIEW

**Comment by phhusson** [comment]
This is only last resort.
Please give logs with HW keymaster

**Comment by SamarV-121** [comment]
Ok

**Comment by SamarV-121** [comment]
https://del.dog/ingimamitt

**Comment by phhusson** [comment]
K please do again a log of the issue on my AOSP v220, without magisk.

**Comment by SamarV-121** [comment]
https://github.com/phhusson/device_phh_treble/pull/198

**Pull request closed without merging**
