### PR TITLE
Fix keylayout for Mi MIX 3

### PR DESCRIPTION
**Pull request by AndroPlus-org**

### CODE REVIEW

**Comment by phhusson** [comment]
AI button should be assistant?

**Comment by AndroPlus-org** [comment]
It was "key 689   AI" and the key starts Xiaomi's original assistant in MIUI.

**Comment by phhusson** [comment]
so yeah send assistant keycode

**Comment by AndroPlus-org** [comment]
OK, changed it to "ASSIST".

**Pull request merged**
