### PR TITLE
[whyred] Add DT2W detection

### PR DESCRIPTION
**Pull request by cheah**
File path is at `/sys/class/input/event2/device/wake_gesture`

### CODE REVIEW

**Comment by phhusson** [comment]
And it's same thing, writing 1 to enable and 0 to disable? (if I remember correctly)

**Comment by cheah** [comment]
In theory, yes, but `echo 1 > /sys/class/input/event2/device/wake_gesture` directly doesn't work on stock kernel by default due to Xiaomi :man_shrugging: 

Writing directly to `/dev/input/event2` in Treble App also doesn't work due to SELinux. I have another patch coming that should fix that.

**Comment by cheah** [comment]
This is the error when trying to toggle dt2w in Treble App after adding the detection

> 12-29 00:02:01.795  9301  9301 D PHH     : Trying to set dt2w mode /dev/input/event2
12-29 00:02:01.790  9301  9301 W .phh.treble.app: type=1400 audit(0.0:276): avc: denied { search } for name="input" dev="tmpfs" ino=18794 scontext=u:r:system_app:s0 tcontext=u:object_r:input_device:s0 tclass=dir permissive=0
12-29 00:02:01.801  9301  9301 D PHH     : Failed setting dt2w mode /dev/input/event2
12-29 00:02:01.801  9301  9301 D PHH     : java.io.FileNotFoundException: /dev/input/event2 (Permission denied)
12-29 00:02:01.801  9301  9301 D PHH     : 	at java.io.FileOutputStream.open0(Native Method)
12-29 00:02:01.801  9301  9301 D PHH     : 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
12-29 00:02:01.801  9301  9301 D PHH     : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
12-29 00:02:01.801  9301  9301 D PHH     : 	at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
12-29 00:02:01.801  9301  9301 D PHH     : 	at me.phh.treble.app.Xiaomi.setDt2w(Xiaomi.kt:28)
12-29 00:02:01.801  9301  9301 D PHH     : 	at me.phh.treble.app.Xiaomi$spListener$1.onSharedPreferenceChanged(Xiaomi.kt:52)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:607)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:489)
12-29 00:02:01.801  9301  9301 D PHH     : 	at androidx.preference.Preference.tryCommit(Preference.java:1632)
12-29 00:02:01.801  9301  9301 D PHH     : 	at androidx.preference.Preference.persistBoolean(Preference.java:1931)
12-29 00:02:01.801  9301  9301 D PHH     : 	at androidx.preference.TwoStatePreference.setChecked(TwoStatePreference.java:92)
12-29 00:02:01.801  9301  9301 D PHH     : 	at androidx.preference.TwoStatePreference.onClick(TwoStatePreference.java:68)
12-29 00:02:01.801  9301  9301 D PHH     : 	at androidx.preference.Preference.performClick(Preference.java:1182)
12-29 00:02:01.801  9301  9301 D PHH     : 	at androidx.preference.Preference.performClick(Preference.java:1166)
12-29 00:02:01.801  9301  9301 D PHH     : 	at androidx.preference.CheckBoxPreference.performClick(CheckBoxPreference.java:90)
12-29 00:02:01.801  9301  9301 D PHH     : 	at androidx.preference.Preference$1.onClick(Preference.java:181)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.view.View.performClick(View.java:6597)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.view.View.performClickInternal(View.java:6574)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.view.View.access$3100(View.java:778)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.view.View$PerformClick.run(View.java:25885)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.os.Handler.handleCallback(Handler.java:873)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.os.Looper.loop(Looper.java:193)
12-29 00:02:01.801  9301  9301 D PHH     : 	at android.app.ActivityThread.main(ActivityThread.java:6718)
12-29 00:02:01.801  9301  9301 D PHH     : 	at java.lang.reflect.Method.invoke(Native Method)
12-29 00:02:01.801  9301  9301 D PHH     : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
12-29 00:02:01.801  9301  9301 D PHH     : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by phhusson** [comment]
well then the property should become /dev/input/event2, if that's where you
need to write to

Le sam. 28 déc. 2019 à 16:35, Michael Cheah <notifications@github.com> a
écrit :

**Comment by cheah** [comment]
This isn't going to work without allowing **system_app** arbitrary writes to **input_device**, which is a pretty bad thing to do.
Thinking of fixing it using another way. Closing this for now.

**Pull request closed without merging**
