### PR TITLE
Fix low brightness issue on realme 2 pro

### PR DESCRIPTION
**Pull request by SamarV-121**

### CODE REVIEW

**Comment by SamarV-121** [comment]
yep 
i tried that but no such property avail* in stock ;_; so did with ro.vendor.product.device

**Comment by phhusson** [comment]
Well please provide the result of "getprop" when running a GSI

**Comment by abchk1234** [comment]
Hi @phhusson 
I have the same device, get following output with AOSP Pie GSI:

~~~~
[af.fast_track_multiplier]: [1]
[audio.adm.buffering.ms]: [4]
[audio.deep_buffer.media]: [true]
[audio.offload.min.duration.secs]: [30]
[audio.offload.video]: [true]
[dalvik.vm.appimageformat]: [lz4]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.dex2oat-minidebuginfo]: [true]
[dalvik.vm.dexopt.secondary]: [true]
[dalvik.vm.heapgrowthlimit]: [384m]
[dalvik.vm.heapmaxfree]: [16m]
[dalvik.vm.heapminfree]: [4m]
[dalvik.vm.heapsize]: [512m]
[dalvik.vm.heapstartsize]: [16m]
[dalvik.vm.heaptargetutilization]: [0.75]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[dalvik.vm.isa.arm.features]: [default]
[dalvik.vm.isa.arm.variant]: [generic]
[dalvik.vm.isa.arm64.features]: [default]
[dalvik.vm.isa.arm64.variant]: [generic]
[dalvik.vm.lockprof.threshold]: [500]
[dalvik.vm.stack-trace-dir]: [/data/anr]
[dalvik.vm.usejit]: [true]
[dalvik.vm.usejitprofiles]: [true]
[debug.atrace.tags.enableflags]: [0]
[debug.force_rtl]: [0]
[debug.gralloc.enable_fb_ubwc]: [1]
[debug.gralloc.gfx_ubwc_disable]: [0]
[debug.hwui.fps_divisor]: [1]
[debug.sf.disable_backpressure]: [1]
[dev.bootcomplete]: [1]
[drm.service.enabled]: [true]
[fastrpc.process.attrs]: [1]
[gr.apk.number]: [5]
[gr.use.leader]: [true]
[gsm.current.phone-type]: [1,1]
[gsm.defaultpdpcontext.active]: [true]
[gsm.lte.ca.support]: [0]
[gsm.network.type]: [Unknown,LTE]
[gsm.operator.alpha]: [,Jio 4G]
[gsm.operator.iso-country]: [,in]
[gsm.operator.isroaming]: [false,false]
[gsm.operator.numeric]: [,405872]
[gsm.serial]: [001832108C14043000015470]
[gsm.sim.operator.alpha]: [,JIO]
[gsm.sim.operator.iso-country]: [,in]
[gsm.sim.operator.numeric]: [,405872]
[gsm.sim.retry.pin1.2]: [3]
[gsm.sim.retry.puk1.2]: [10]
[gsm.sim.state]: [,LOADED]
[gsm.version.baseband]: [Q_V1_P14,Q_V1_P14]
[gsm.version.ril-impl]: [Qualcomm RIL 1.0]
[hwservicemanager.ready]: [true]
[init.svc.adbd]: [running]
[init.svc.adsprpcd]: [running]
[init.svc.alarm-hal-1-0]: [running]
[init.svc.audio-hal-2-0]: [running]
[init.svc.audioserver]: [running]
[init.svc.bluetooth-1-0]: [running]
[init.svc.bootanim]: [stopped]
[init.svc.camera-provider-2-4]: [running]
[init.svc.cameraserver]: [running]
[init.svc.cas-hal-1-0]: [running]
[init.svc.cnd]: [running]
[init.svc.cnss-daemon]: [running]
[init.svc.cnss_diag]: [stopped]
[init.svc.configstore-hal-1-0]: [running]
[init.svc.crashdata-sh]: [stopped]
[init.svc.display-color-hal-1-0]: [running]
[init.svc.dpmQmiMgr]: [running]
[init.svc.drm]: [running]
[init.svc.drm-hal-1-0]: [running]
[init.svc.drm-widevine-hal-1-0]: [running]
[init.svc.energy-awareness]: [stopped]
[init.svc.engineer_shell]: [stopped]
[init.svc.face_hal]: [stopped]
[init.svc.fpay_hal]: [running]
[init.svc.fps_hal]: [stopped]
[init.svc.gatekeeper-1-0]: [running]
[init.svc.gatekeeperd]: [running]
[init.svc.gralloc-2-0]: [running]
[init.svc.hal_cryptoeng_oppo]: [running]
[init.svc.health-hal-1-0]: [running]
[init.svc.healthd]: [running]
[init.svc.hidl_memory]: [running]
[init.svc.hwcomposer-2-1]: [running]
[init.svc.hwservicemanager]: [running]
[init.svc.ims_rtp_daemon]: [running]
[init.svc.imsdatadaemon]: [running]
[init.svc.imsqmidaemon]: [running]
[init.svc.incidentd]: [stopped]
[init.svc.installd]: [running]
[init.svc.ipacm]: [running]
[init.svc.ipacm-diag]: [running]
[init.svc.irsc_util]: [stopped]
[init.svc.keymaster-3-0]: [running]
[init.svc.keystore]: [running]
[init.svc.ktv-hal-1-0]: [stopped]
[init.svc.light-hal-2-0]: [running]
[init.svc.lmkd]: [running]
[init.svc.loc_launcher]: [running]
[init.svc.logd]: [running]
[init.svc.logd-reinit]: [stopped]
[init.svc.media]: [running]
[init.svc.mediacodec]: [running]
[init.svc.mediadrm]: [running]
[init.svc.mediaextractor]: [running]
[init.svc.mediametrics]: [running]
[init.svc.memtrack-hal-1-0]: [running]
[init.svc.mlid]: [running]
[init.svc.netd]: [running]
[init.svc.netmgrd]: [running]
[init.svc.oppo_fingerprints_sh]: [stopped]
[init.svc.oppoalgo]: [running]
[init.svc.pd_mapper]: [running]
[init.svc.per_mgr]: [running]
[init.svc.per_proxy]: [running]
[init.svc.perf-hal-1-0]: [running]
[init.svc.perfprofd]: [running]
[init.svc.phh_on_boot]: [stopped]
[init.svc.power-hal-1-0]: [running]
[init.svc.ppd]: [running]
[init.svc.prop-adap-core]: [stopped]
[init.svc.prop-adap-main]: [stopped]
[init.svc.qcom-c_core-sh]: [stopped]
[init.svc.qcom-c_main-sh]: [stopped]
[init.svc.qcom-post-boot]: [stopped]
[init.svc.qcom-sh]: [stopped]
[init.svc.qcom-usb-sh]: [stopped]
[init.svc.qdutils_disp-1-0]: [running]
[init.svc.qfp-daemon]: [running]
[init.svc.qseecomd]: [running]
[init.svc.qteeconnector-hal-1-0]: [running]
[init.svc.qti_esepowermanager_service]: [running]
[init.svc.qti_gnss_service]: [running]
[init.svc.qvop-daemon]: [running]
[init.svc.remosaic]: [running]
[init.svc.ril-daemon]: [running]
[init.svc.ril-daemon2]: [running]
[init.svc.rmt_storage]: [running]
[init.svc.seemp_healthd]: [running]
[init.svc.sensor-sh]: [stopped]
[init.svc.sensors]: [running]
[init.svc.sensors-hal-1-0]: [running]
[init.svc.servicemanager]: [running]
[init.svc.statsd]: [stopped]
[init.svc.storaged]: [running]
[init.svc.surfaceflinger]: [running]
[init.svc.tftp_server]: [running]
[init.svc.thermal-engine]: [running]
[init.svc.thermal-hal-1-0]: [running]
[init.svc.thermalservice]: [running]
[init.svc.time_daemon]: [running]
[init.svc.tombstoned]: [running]
[init.svc.tui_comm-1-0]: [running]
[init.svc.ueventd]: [running]
[init.svc.usb-hal-1-0]: [running]
[init.svc.usbd]: [stopped]
[init.svc.vendor.imsrcsservice]: [stopped]
[init.svc.vendor.msm_irqbalance]: [running]
[init.svc.vibrator-1-0]: [running]
[init.svc.vndservicemanager]: [running]
[init.svc.vold]: [running]
[init.svc.vr_hwc]: [running]
[init.svc.wifi_hal_legacy]: [running]
[init.svc.wificond]: [running]
[init.svc.wifiserver]: [stopped]
[init.svc.wpa_supplicant]: [stopped]
[init.svc.zygote]: [running]
[init.svc.zygote_secondary]: [running]
[is_can_remove_themespacelib]: [1]
[keyguard.no_require_sim]: [true]
[log.tag.WifiHAL]: [D]
[net.bt.name]: [Android]
[net.qtaguid_enabled]: [1]
[net.tcp.2g_init_rwnd]: [10]
[net.tcp.buffersize.default]: [4096,87380,524288,4096,16384,110208]
[net.tcp.buffersize.edge]: [4093,26280,35040,4096,16384,35040]
[net.tcp.buffersize.evdo]: [4094,87380,524288,4096,16384,262144]
[net.tcp.buffersize.gprs]: [4092,8760,11680,4096,8760,11680]
[net.tcp.buffersize.hsdpa]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.hspa]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.hspap]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.hsupa]: [4094,87380,1220608,4096,16384,1220608]
[net.tcp.buffersize.lte]: [2097152,4194304,8388608,262144,524288,1048576]
[net.tcp.buffersize.umts]: [4094,87380,110208,4096,16384,110208]
[net.tcp.buffersize.wifi]: [524288,2097152,4194304,262144,524288,1048576]
[net.tcp.default_init_rwnd]: [60]
[persist.bt.iot.enablelogging]: [true]
[persist.bt.soc.alwayson]: [true]
[persist.cne.subscription_aware]: [false]
[persist.data.iwlan.enable]: [true]
[persist.data.iwlan.rekey]: [4294967295]
[persist.dirac.acs.controller]: [qem]
[persist.dirac.acs.ignore_error]: [1]
[persist.healthd.storeprops]: [true]
[persist.nfc.smartcard.config]: [SIM1]
[persist.power.useautobrightadj]: [true]
[persist.radio.apm_sim_not_pwdn]: [1]
[persist.radio.custom_exp_ecc]: [1]
[persist.radio.multisim.config]: [dsds]
[persist.rcs.supported]: [0]
[persist.sys.adddevdiag]: [0]
[persist.sys.assert.enabletip]: [0]
[persist.sys.assert.panic]: [false]
[persist.sys.assert.state]: [false]
[persist.sys.autostoplog]: [1]
[persist.sys.cfu_auto]: [1]
[persist.sys.dalvik.vm.lib.2]: [libart.so]
[persist.sys.disable_rescue]: [true]
[persist.sys.displayinset.top]: [0]
[persist.sys.dump]: [0]
[persist.sys.elsa.enable]: [299]
[persist.sys.elsa.kernel_enable]: [1]
[persist.sys.enable.neo]: [1]
[persist.sys.gps.lpp]: [0]
[persist.sys.hardcoder.name]: [oiface]
[persist.sys.locale]: [en-US]
[persist.sys.log.event]: [20|2]
[persist.sys.log.kernel]: [50|30]
[persist.sys.log.main]: [50|20]
[persist.sys.log.radio]: [20|5]
[persist.sys.log.tcpdump]: [100|10]
[persist.sys.log.user]: [1]
[persist.sys.max_aspect_ratio.pre_o]: [1.86]
[persist.sys.nw_lab_test]: [0]
[persist.sys.nw_mbn_icon]: [0]
[persist.sys.oem_smooth]: [1]
[persist.sys.oiface.enable]: [2]
[persist.sys.oiface.feature]: [oiface:1f,oifaceim:ffffffff]
[persist.sys.oppo.fatal]: [1]
[persist.sys.oppo.junklog]: [false]
[persist.sys.oppo.junkmonitor]: [true]
[persist.sys.oppo.log.config]: [0]
[persist.sys.oppo.longpwk]: []
[persist.sys.oppo.qx.config]: [7]
[persist.sys.oppo.region]: [US]
[persist.sys.oppodebug.tpcatcher]: [14]
[persist.sys.overlay.devinputjack]: [true]
[persist.sys.overlay.nightmode]: [true]
[persist.sys.phh.ims.caf]: [false]
[persist.sys.qcom-brightness]: [4095]
[persist.sys.signal.level]: [default]
[persist.sys.timezone]: [Asia/Kolkata]
[persist.sys.usb.config]: [adb]
[persist.sys.usb.config.extra]: [none]
[persist.sys.usb.ffbm-00.func]: [diag]
[persist.sys.usb.ffbm-01.func]: [diag]
[persist.sys.usb.ffbm-02.func]: [diag]
[persist.sys.usb.reboot.func]: [adb]
[persist.sys.vndk]: [27]
[persist.sys.webview.vmsize]: [147551200]
[persist.sys.wifipacketlog.state]: [false]
[persist.vendor.audio.fluence.speaker]: [true]
[persist.vendor.audio.fluence.voicecall]: [true]
[persist.vendor.audio.fluence.voicerec]: [false]
[persist.vendor.audio.hifi.int_codec]: [true]
[persist.vendor.audio.ras.enabled]: [false]
[persist.vendor.radio.adb_log_on]: [0]
[persist.vendor.radio.cs_srv_type]: [1]
[persist.vendor.radio.custom_ecc]: [1]
[persist.vendor.radio.force_on_dc]: [true]
[persist.vendor.radio.lte_vrte_ltd]: [1]
[persist.vendor.radio.msim.stackid_0]: [0]
[persist.vendor.radio.msim.stackid_1]: [1]
[persist.vendor.radio.process_sups_ind]: [1]
[persist.vendor.radio.rat_on]: [combine]
[persist.vendor.radio.report_codec]: [1]
[persist.vendor.radio.ril_payload_on]: [0]
[persist.vendor.radio.sglte_target]: [0]
[persist.vendor.radio.sib16_support]: [1]
[persist.vendor.radio.stack_id_0]: [0]
[persist.vendor.radio.stack_id_1]: [1]
[persist.version.confidential]: [false]
[pm.dexopt.ab-ota]: [speed-profile]
[pm.dexopt.bg-dexopt]: [speed-profile]
[pm.dexopt.boot]: [verify]
[pm.dexopt.core-app]: [speed]
[pm.dexopt.first-boot]: [quicken]
[pm.dexopt.inactive]: [verify]
[pm.dexopt.install]: [quicken]
[pm.dexopt.priv-apps-oob]: [false]
[pm.dexopt.priv-apps-oob-list]: [ALL]
[pm.dexopt.shared]: [speed]
[qcom.bluetooth.soc]: [cherokee]
[qemu.hw.mainkeys]: [0]
[ril.ecclist]: [911,112,000,08,110,118,119,999,122,120]
[ril.ecclist1]: [911,112,000,08,110,118,119,999,122,120,100,101,102,108]
[ril.qcril_pre_init_lock_held]: [0]
[ril.vendor.radio.db_upgrade]: [1]
[rild.libpath]: [/vendor/lib64/libril-qc-hal-qmi.so]
[ro.actionable_compatible_property.enabled]: [false]
[ro.adb.secure]: [0]
[ro.allow.mock.location]: [0]
[ro.art.hiddenapi.warning]: [1]
[ro.baseband]: [sdm]
[ro.bionic.ld.warning]: [1]
[ro.board.platform]: [sdm660]
[ro.boot.baseband]: [sdm]
[ro.boot.bootdevice]: [c0c4000.sdhci]
[ro.boot.configfs]: [true]
[ro.boot.console]: [ttyMSM0]
[ro.boot.flash.locked]: [0]
[ro.boot.hardware]: [qcom]
[ro.boot.keymaster]: [1]
[ro.boot.mode]: [reboot]
[ro.boot.startupmode]: [hard_reset]
[ro.boot.usbcontroller]: [a800000.dwc3]
[ro.boot.verifiedbootstate]: [orange]
[ro.boot.veritymode]: [enforcing]
[ro.bootimage.build.date]: [Tue Mar 5 14:28:38 UTC 2019]
[ro.bootimage.build.date.utc]: [1551796118]
[ro.bootloader]: [unknown]
[ro.bootmode]: [reboot]
[ro.build.characteristics]: [default]
[ro.build.date]: [Fri Feb 15 12:24:07 CST 2019]
[ro.build.date.Ymd]: [190215]
[ro.build.date.YmdHM]: [201902151143]
[ro.build.date.utc]: [1550204647]
[ro.build.date.ymd]: [190215]
[ro.build.description]: [treble_arm64_avN-userdebug 9 PQ2A.190305.002 190305 test-keys]
[ro.build.display.full_id]: [RMX1801_11_A.16_190215]
[ro.build.display.id]: [RMX1801EX_11_A.16]
[ro.build.fingerprint]: [Android/treble_arm64_avN/phhgsi_arm64_a:9/PQ2A.190305.002/190305:userdebug/test-keys]
[ro.build.flavor]: [treble_arm64_avN-userdebug]
[ro.build.host]: [ecb7a332f1d0]
[ro.build.id]: [PQ2A.190305.002]
[ro.build.kernel.id]: [4.4.78]
[ro.build.master.date]: [201902151143]
[ro.build.product]: [RMX1801]
[ro.build.release_type]: [true]
[ro.build.soft.daily.version]: [false]
[ro.build.soft.majorversion]: []
[ro.build.soft.version]: [A.16]
[ro.build.tags]: [test-keys]
[ro.build.type]: [userdebug]
[ro.build.user]: [jenkins]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.codename]: [REL]
[ro.build.version.incremental]: [1550204647]
[ro.build.version.min_supported_target_sdk]: [17]
[ro.build.version.opporom]: [V5.2]
[ro.build.version.ota]: [RMX1801EX_11.A.16_0160_201902151143]
[ro.build.version.preview_sdk]: [0]
[ro.build.version.release]: [9]
[ro.build.version.sdk]: [28]
[ro.build.version.security_patch]: [2019-03-05]
[ro.camera.dualcam.type]: [2]
[ro.camera.hfr.enable]: [1]
[ro.camera.sensor.aux2m]: [1]
[ro.camera.temperature.limit]: [450]
[ro.carrier]: [unknown]
[ro.com.android.dataroaming]: [true]
[ro.com.google.gmsversion]: [8.1_201808]
[ro.commonsoft.bootanimation]: [realme]
[ro.commonsoft.product]: [device1]
[ro.config.alarm_alert]: [Alarm_Classic.ogg]
[ro.config.calendar_sound]: [notification_003.ogg]
[ro.config.notification_sim2]: [notification_000.ogg]
[ro.config.notification_sms]: [notification_000.ogg]
[ro.config.notification_sound]: [pixiedust.ogg]
[ro.config.ringtone]: [Ring_Synth_04.ogg]
[ro.config.ringtone_sim2]: [ringtone_000.ogg]
[ro.control_privapp_permissions]: [disable]
[ro.cp_system_other_odex]: [0]
[ro.crypto.state]: [unencrypted]
[ro.cust.cdrom]: [/dev/null]
[ro.cutoff_voltage_mv]: [3200]
[ro.dalvik.vm.native.bridge]: [0]
[ro.debuggable]: [1]
[ro.dirac.acs.storeSettings]: [1]
[ro.display.rc.size]: [108,108,111,111]
[ro.dumpenvironment.time]: [10000]
[ro.elsa]: [true]
[ro.frp.pst]: [/dev/block/bootdevice/by-name/frp]
[ro.hardware]: [qcom]
[ro.hardware.nfc_nci]: [cxd22xx.default]
[ro.kernelhotfix.sha]: [2f2adc378a608feeec925dcd8bfd06d1599347c8 picked]
[ro.keymaster.mod]: [AOSP on ARM64]
[ro.keymaster.xxx.release]: [8.1.0]
[ro.keymaster.xxx.security_patch]: [2019-02-01]
[ro.lcd.backlight.dpt_twelvebit]: [11,662,40,170,266,490,783,1213,1905,2391,3447,4095]
[ro.lcd.backlight.himaxs_twelvebit]: [11,662,40,170,266,490,783,1213,1905,2391,3447,4095]
[ro.lcd.backlight.tianma_twelvebit]: [11,662,40,170,266,490,783,1213,1905,2391,3447,4095]
[ro.logd.auditd]: [true]
[ro.logdumpd.enabled]: [0]
[ro.oem_unlock_supported]: [true]
[ro.opa.eligible_device]: [true]
[ro.oppo.market.name]: [Realme 2 Pro]
[ro.oppo.network.serialno]: [1c16c4b5]
[ro.oppo.screen.heteromorphism]: [444,0:636,76]
[ro.oppo.theme.version]: [805]
[ro.oppo.version]: [US]
[ro.product.authentication]: [0]
[ro.product.board]: [sdm660]
[ro.product.brand]: [OPPO]
[ro.product.brand.sub]: [Realme]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.device]: [RMX1801]
[ro.product.first_api_level]: [27]
[ro.product.locale]: [en-US]
[ro.product.manufacturer]: [unknown]
[ro.product.model]: [RMX1801]
[ro.product.operatorname]: [5]
[ro.product.prjversion]: [18321]
[ro.property_service.version]: [2]
[ro.qcom.ad]: [1]
[ro.qcom.ad.calib.data]: [/vendor/etc/OPPO_OLED_AD_calib.cfg]
[ro.qcom.ad.sensortype]: [2]
[ro.qualcomm.foss]: [0]
[ro.revision]: [0]
[ro.rf_version]: [W_G_L_18321]
[ro.script.version]: [1.0]
[ro.secure]: [1]
[ro.separate.soft]: [18321]
[ro.setupwizard.mode]: [OPTIONAL]
[ro.setupwizard.rotation_locked]: [true]
[ro.sf.lcd_density]: [480]
[ro.sys.reserve.integrate]: [true]
[ro.sys.sdcardfs]: [true]
[ro.telephony.call_ring.multiple]: [false]
[ro.telephony.default_network]: [9,0]
[ro.treble.enabled]: [true]
[ro.vendor.audio.sdk.fluencetype]: [none]
[ro.vendor.audio.sdk.ssr]: [false]
[ro.vendor.build.date]: [Fri Feb 15 12:22:20 CST 2019]
[ro.vendor.build.date.utc]: [1550204540]
[ro.vendor.extension_library]: [libqti-perfd-client.so]
[ro.vendor.product.brand]: [OPPO]
[ro.vendor.product.device]: [RMX1801]
[ro.vendor.product.manufacturer]: [OPPO]
[ro.vendor.product.model]: [RMX1801]
[ro.vendor.product.oem]: [RMX1801]
[ro.vendor.ril.svdo]: [false]
[ro.vendor.ril.svlte1x]: [false]
[ro.vendor.sdk.sensors.gestures]: [false]
[ro.vendor.sensors.cmc]: [false]
[ro.vendor.sensors.facing]: [false]
[ro.vendor.sensors.wu]: [false]
[ro.vndk.version]: [27]
[ro.vold.serialno]: [1c16c4b5]
[ro.wifi.channels]: []
[ro.xxversion]: [V0.5]
[ro.zygote]: [zygote64_32]
[security.perf_harden]: [1]
[selinux.restorecon_recursive]: [/data/misc_ce/0]
[service.bootanim.exit]: [1]
[service.sf.present_timestamp]: [1]
[sys.autosuspend.timeout]: [500000]
[sys.boot_completed]: [1]
[sys.foreground_process]: [android]
[sys.listeners.registered]: [true]
[sys.logbootcomplete]: [1]
[sys.oem_unlock_allowed]: [1]
[sys.oppo.hasPhysicalGyroscope]: [true]
[sys.oppo_ftm_mode]: [0]
[sys.post_boot.parsed]: [1]
[sys.retaildemo.enabled]: [0]
[sys.sysctl.extra_free_kbytes]: [29615]
[sys.sysctl.tcp_def_init_rwnd]: [60]
[sys.uidcpupower]: []
[sys.usb.config]: [adb]
[sys.usb.ffs.aio_compat]: [true]
[sys.usb.ffs.ready]: [1]
[sys.usb.rmnet.func.name]: [rmnet_bam]
[sys.usb.rndis.func.name]: [rndis_bam]
[sys.usb.rps_mask]: [0]
[sys.usb.state]: [adb]
[sys.user.0.ce_available]: [true]
[sys.vendor.shutdown.waittime]: [500]
[sys.wifitracing.started]: [1]
[tombstoned.max_tombstone_count]: [50]
[vendor.audio.dolby.ds2.enabled]: [false]
[vendor.audio.dolby.ds2.hardbypass]: [false]
[vendor.audio.flac.sw.decoder.24bit]: [true]
[vendor.audio.hw.aac.encoder]: [true]
[vendor.audio.noisy.broadcast.delay]: [600]
[vendor.audio.offload.buffer.size.kb]: [64]
[vendor.audio.offload.gapless.enabled]: [true]
[vendor.audio.offload.multiaac.enable]: [true]
[vendor.audio.offload.multiple.enabled]: [false]
[vendor.audio.offload.passthrough]: [false]
[vendor.audio.offload.pstimeout.secs]: [3]
[vendor.audio.offload.track.enable]: [true]
[vendor.audio.parser.ip.buffer.size]: [262144]
[vendor.audio.safx.pbe.enabled]: [true]
[vendor.audio.tunnel.encode]: [false]
[vendor.audio.use.sw.alac.decoder]: [true]
[vendor.audio.use.sw.ape.decoder]: [true]
[vendor.audio_hal.period_size]: [192]
[vendor.fm.a2dp.conc.disabled]: [true]
[vendor.voice.path.for.pcm.voip]: [true]
[video.disable.ubwc]: [1]
[vold.has_adoptable]: [0]
[vold.has_quota]: [1]
[vold.has_reserved]: [0]
[vold.post_fs_data_done]: [1]
[wifi.interface]: [wlan0]
~~~~

If anything else is needed please let me know. Thank you.

**Review by CODES77 — COMMENTED** [review]
CODES77

**Review by CODES77 — CHANGES_REQUESTED** [review]
CODES77

**Pull request closed without merging**
