### PR TITLE
[Motorola One Fusion+] Fix bluetooth audio

### PR DESCRIPTION
**Pull request by ksdrar**
**Required Phh Treble Settings:**
- Use alternate audio policy
- Disable audio effects
- Force-disable A2DP offload

Tested on v400.h and Pixel Experience 12.0 v402.1

### CODE REVIEW

**Comment by phhusson** [comment]
Ok on the idea, I just don't want to hard-code the line number, because there is no reason for it to be stable.
Please show me your original /vendor/etc/audio_policy_configuration.xml ; I'll edit the sed command to be more robust

**Comment by ksdrar** [comment]
This is the original:  https://pastebin.com/sQ5fN09N

**Comment by phhusson** [comment]
Ok, so for your sed, please try this. I'm not really sure of the syntax. Maybe you need `a` rather than `i` or something else

```
sed -i '/r_submix_audio_policy_configuration/i <xi:include href="/vendor/etc/a2dp_audio_policy_configuration.xml"/>' /mnt/phh/audio_policy_configuration.xml
```

**Comment by ksdrar** [comment]
It's working fine

**Comment by phhusson** [comment]
Thank you for that fix.
I'll look to expand it to other devices.

With regards to "Required Phh Treble Settings:", you can add those settings for your device in https://github.com/phhusson/treble_presets/

**Pull request merged**
