### PR TITLE
Fix dualsim for some Huawei phones

### PR DESCRIPTION
**Pull request by washinson**
Huawei P20 Lite doesn't have /odm/phone.prop, we must use /vendor/phone.prop

### CODE REVIEW

**Comment by phhusson** [comment]
Shit, my original code is wrong, it uses hardcoded value!

Is your awk code identical to mine except for the wrong id?

**Comment by washinson** [comment]
My awk identical your except wrong id and new path /vendor/phone.prop

**Comment by phhusson** [comment]
Does this work:
```
#Weird /odm/phone.prop Huawei stuff
HW_PRODID="$(sed -nE 's/.*productid=([0-9x]*).*/\1/p' /proc/cmdline)"
[ -z "$HW_PRODID" ] && HW_PRODID="0x$(od -A none -t x1 /sys/firmware/devicetree/base/hisi,modem_id | sed s/' '//g)"
for part in odm vendor;do
    if [ -f /$part/phone.prop ];then
        if [ -n "$HW_PRODID" ];then
            eval "$(awk 'BEGIN { a=0 }; /\[.*\].*/ { a=0 }; tolower($0) ~ /.*'"$HW_PRODID"'.*/ { a=1 }; /.*=.*/ { if(a == 1) print $0 }' /$part/phone.prop |sed -nE 's/(.*)=(.*)/setprop \1 "\2";/p')"
        fi
    fi
done
```

?

**Comment by washinson** [comment]
Infinity loop

**Comment by washinson** [comment]
Your code to detect product id is incorrect
```
/system_root/system/bin # cat /proc/cmdline
loglevel=4 coherent_pool=512K page_tracker=on slub_min_objects=12 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user androidboot.swtype=normal fastboot_version=Chipset-chicago9.1.0.6(0A85)_FASTBOOT setup_logctl=0 enter_recovery=1 enter_erecovery=1 androidboot.mode=normal pmu_nv_addr=0x34a20014 low_volt_flag=0 usb_macbt=normal boardid=0x0000136a androidboot.dtbo_idx=0 normal_reset_type=BR_KEY_VOLUMN_UP  TP_COLOR=0  COLOR_TMP=0 LCD_DENSITY=0  DDIC_INFO= productid=0x3b697815 androidboot.serialno=9WVDU18723001671 himntn=01111111111110100010110000000000000000101000 boot_slice=0x00084c46 reboot_reason=COLDBOOT exception_subtype=no last_bootup_keypoint=32 recovery_update=1 bootlock=unlocked hw_bfm_enable=0 hw_bfr_enable=1 swiotlb=2 androidboot.odm.conn.chiptype=hisi androidboot.odm.conn.schiptype=hi1102 mdmreglogbase=0x00000000 mdmreglogsize=0x00000000 modem_socp_enable=0 androidboot.hardware=hi6250 tpcolor=black emmc_freqsel=0x00000010 format_data=1 erecovery_enter_reason=2001 cpu_buck_reg=0x;;  LCD_ID=0 androidboot.vendor.ddrsize=4 oba_version=20191106213659_OBA_VERSION kce_status=1 androidboot.verifiedbootstate=orange androidboot.veritymode=enforcing efuse_status=0  androidboot.vercnt1=0 bl1_time=1513 bl2_time=16648 logo_time=8960 dsm_notify=0 backcolor=black vendorcountry=hw/ru devmodel=ANE-L21 userHotaUpdate=success_2 androidboot.product.hardware.sku=ANE-L21 userlock=unlocked androidboot.oemmode=user cache=PARTUUID=f9f21f2a-a8d4-5f0e-9746-594869aec34e/recovery/ patch=PARTUUID=f9f21f2f-a8d4-5f0e-9746-594869aec34e  LCD_ELVSS_DIM=0  console=ttyS0
/system_root/system/bin # echo $(sed -nE 's/.*productid=([0-9x]*).*/\1/p' /proc/cmdline)
0x3
/system_root/system/bin #
```

**Comment by washinson** [comment]
> 
> 
> Infinity loop

?or very long boot?
With correct product ID phone loaded normally and dualsim worked

**Comment by phhusson** [comment]
Oh I see. Is productid=0x3b697815 correct? 
I believe adding a-f in the number matching should fix this

**Comment by washinson** [comment]
Ok, this code works
```
#Weird /odm/phone.prop Huawei stuff
HW_PRODID="$(sed -nE 's/.*productid=([0-9xa-f]*).*/\1/p' /proc/cmdline)"
[ -z "$HW_PRODID" ] && HW_PRODID="0x$(od -A none -t x1 /sys/firmware/devicetree/base/hisi,modem_id | sed s/' '//g)"
for part in odm vendor;do
    if [ -f /$part/phone.prop ];then
        if [ -n "$HW_PRODID" ];then
            eval "$(awk 'BEGIN { a=0 }; /\[.*\].*/ { a=0 }; tolower($0) ~ /.*'"$HW_PRODID"'.*/ { a=1 }; /.*=.*/ { if(a == 1) print $0 }' /$part/phone.prop |sed -nE 's/(.*)=(.*)/setprop \1 "\2";/p')"
        fi
    fi
done
```

**Pull request merged**
