### PR TITLE
fp-gestures: don't change if exists

### PR DESCRIPTION
**Pull request by eremitein**
bad idea to delete users changes after reboot
no need to anger users:)

	modified:   rw-system.sh

### CODE REVIEW

**Comment by phhusson** [comment]
/mnt/phh is in RAM, how does the user keep changes?

Also what's the use case?

**Comment by eremitein** [comment]
> /mnt/phh is in RAM, how does the user keep changes?
> 
> Also what's the use case?

use case: I put the uinput file with my settings in TWRP seance, rebooted - my file disappeared for system and was replaced with an empty one (arghhhh!!)

when I fixed the rw-system.sh, my file remained after the reboot and I could use it

**Comment by phhusson** [comment]
That's not a use case.

Why did you change that file for?

**Comment by eremitein** [comment]
> Why did you change that file for? 

for set my personal fp gestures)

i guess, this is abnormal - deleting user's settings

changes in rw-system.sh fixed that. and this is absolutely safely, script logic not broken for new installations when uinput files not exists

**Review by penn5 — CHANGES_REQUESTED** [review]
It has no effect, if statement always true

**Comment by phhusson** [comment]
To answer my question, there is a `cp -a` from system to tmpfs, hence it's working

**Pull request merged**
