### PR TITLE
[Android 10][Begonia] Fix brightness and fingerprint sensor on Redmi Note 8 Pro

### PR DESCRIPTION
**Pull request by jumper047**
Fix for phhusson/treble_experimentations#1019

### CODE REVIEW

**Comment by phhusson** [comment]
Is this actually tested? `*.` is weird at best

**Comment by jumper047** [comment]
Yes, tested in adb shell and seems working. 
```
root@begonia:/ # getprop ro.vendor.build.fingerprint | grep -i -e Redmi/*.begonia                                                                                        
Redmi/begonia_ru/begonia:9/PPR1.180610.011/V11.0.1.0.PGGRUXM:user/release-keys
```
**UPD** Sorry, double checked it and seems like dot is redundant.

**Comment by jumper047** [comment]
I think just Redmi/begonia will be enough. Ill fix it after work day.

**Comment by jumper047** [comment]
I simplifyed regexp and added fingerprint fix.

**Pull request merged**
