### PR TITLE
rw-system: add 'daisy' stock keylayout files

### PR DESCRIPTION
**Pull request by eremitein**
modified:   base.mk
	new file:   files/daisy-buttonJack.kl
	new file:   files/daisy-uinput-fpc.kl
	new file:   files/daisy-uinput-goodix.kl
	modified:   rw-system.sh

### CODE REVIEW

**Comment by phhusson** [comment]
Why?

**Comment by eremitein** [comment]
1-2. because gestures not works (exist in some gsi, same as stock - swipe for notifications)
3. daisy-buttonJack.kl need for headphones volume control by buttons

**Comment by phhusson** [comment]
Say so in the commit

**Comment by eremitein** [comment]
> Say so in the commit

done

**Pull request merged**
